name: Build Exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Check versions
      run: |
        node -v
        npm -v
        python -V

    - name: Install dependencies
      run: pip install pyinstaller

    - name: Build exe for pars.py
      run: pyinstaller --onefile pars.py
      working-directory: ${{ github.workspace }}

    - name: Build exe for skladnia-json.py
      run: pyinstaller --onefile skladnia-json.py
      working-directory: ${{ github.workspace }}

    - name: Build exe for zgodnosc-json.py
      run: pyinstaller --onefile zgodnosc-json.py
      working-directory: ${{ github.workspace }}

    - name: Build exe for yaml_weryfikacja.py
      run: pyinstaller --onefile yaml_weryfikacja.py
      working-directory: ${{ github.workspace }}

    - name: Build exe for zgodnosc-yaml.py
      run: pyinstaller --onefile zgodnosc-yaml.py
      working-directory: ${{ github.workspace }}

    - name: Build exe for weryfikacja-xml.py
      run: pyinstaller --onefile weryfikacja-xml.py
      working-directory: ${{ github.workspace }}

    - name: Build exe for zgodnosc-xml.py
      run: pyinstaller --onefile zgodnosc-xml.py
      working-directory: ${{ github.workspace }}

    - name: Upload exe files
      uses: actions/upload-artifact@v4
      with:
        name: exe-files
        path: |
          dist/pars
          dist/skladnia-json
          dist/zgodnosc-json
          dist/weryfikacja-yaml
          dist/zgodnosc-yaml
          dist/weryfikacja-xml
          dist/zgodnosc-xml
